### ISSUE TITLE
Le style "code" doit avoir une taille de 1.2em dans les corps de message

### ISSUE THREAD

**Issue by eunomie** [eunomie/linuxfr-solarized#19]
Appliquer le style des commentaires en fait :

``` css
.threads code {
  font-size: 1.2em;
}
article code {
  font-size: 1.6em;
}
```
