### ISSUE TITLE
Mieux placer le sommaire

### ISSUE THREAD

**Issue by eunomie** [eunomie/linuxfr-solarized#4]
Améliorer le placement du sommaire :
- décaler le titre
- avoir le sommaire en un bloc, non influencé par le float de l'avatar
- un peu plus d'espace avant le titre "sommaire"

``` css
#sommaire {
  margin-top: 0.5em;
  margin-left: 80px;
}
#sommaire + ul {
  margin-left: 80px;
}
```
